pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'git@github-personal:jonaleo87/plaid-postman-automation.git'
            }
        }

        stage('Install Newman') {
            steps {
                sh 'npm install -g newman'
            }
        }

        stage('Run Postman Tests') {
            steps {
                sh 'newman run postman-collection/Plaid-Sandbox-API.postman_collection.json -e postman-collection/Sandbox-Plaid.postman_environment.json'
            }
        }
    }

    post {
        always {
            junit 'newman/*.xml'
        }
    }
}